// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	hcloudclient "github.com/syself/cluster-api-provider-hetzner/pkg/services/hcloud/client"
)

// Factory is an autogenerated mock type for the Factory type
type Factory struct {
	mock.Mock
}

type Factory_Expecter struct {
	mock *mock.Mock
}

func (_m *Factory) EXPECT() *Factory_Expecter {
	return &Factory_Expecter{mock: &_m.Mock}
}

// NewClient provides a mock function with given fields: hcloudToken, opts
func (_m *Factory) NewClient(hcloudToken string, opts ...hcloudclient.ClientOption) hcloudclient.Client {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, hcloudToken)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for NewClient")
	}

	var r0 hcloudclient.Client
	if rf, ok := ret.Get(0).(func(string, ...hcloudclient.ClientOption) hcloudclient.Client); ok {
		r0 = rf(hcloudToken, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(hcloudclient.Client)
		}
	}

	return r0
}

// Factory_NewClient_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NewClient'
type Factory_NewClient_Call struct {
	*mock.Call
}

// NewClient is a helper method to define mock.On call
//   - hcloudToken string
//   - opts ...hcloudclient.ClientOption
func (_e *Factory_Expecter) NewClient(hcloudToken interface{}, opts ...interface{}) *Factory_NewClient_Call {
	return &Factory_NewClient_Call{Call: _e.mock.On("NewClient",
		append([]interface{}{hcloudToken}, opts...)...)}
}

func (_c *Factory_NewClient_Call) Run(run func(hcloudToken string, opts ...hcloudclient.ClientOption)) *Factory_NewClient_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]hcloudclient.ClientOption, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(hcloudclient.ClientOption)
			}
		}
		run(args[0].(string), variadicArgs...)
	})
	return _c
}

func (_c *Factory_NewClient_Call) Return(_a0 hcloudclient.Client) *Factory_NewClient_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Factory_NewClient_Call) RunAndReturn(run func(string, ...hcloudclient.ClientOption) hcloudclient.Client) *Factory_NewClient_Call {
	_c.Call.Return(run)
	return _c
}

// NewFactory creates a new instance of Factory. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewFactory(t interface {
	mock.TestingT
	Cleanup(func())
}) *Factory {
	mock := &Factory{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
